// mise-en-place/app/budgets.jsx
// Budgets page.

const BD = window.MEP_DATA;
const BI = window.MEPIcons;

function MEPBudgets() {
  // Use the budgets data, extended with bigger set
  const budgets = [
    ...BD.budgets,
    { cat: 'Pan', color: '#6a6660', limit: 700, spent: 612.80 },
    { cat: 'Limpieza', color: '#3a6a7a', limit: 600, spent: 384.10 },
    { cat: 'Bebidas no alcohólicas', color: '#6a4a6a', limit: 800, spent: 412.40 },
    { cat: 'Consumibles cocina', color: '#8a8275', limit: 400, spent: 218.30 },
  ];
  const totalLimit = budgets.reduce((s, b) => s + b.limit, 0);
  const totalSpent = budgets.reduce((s, b) => s + b.spent, 0);
  const totalPct = (totalSpent / totalLimit) * 100;

  const status = (pct) => pct < 80 ? 'pos' : (pct <= 100 ? 'warn' : 'neg');
  const semColor = {
    pos: 'var(--mep-pos)', warn: 'var(--mep-warn)', neg: 'var(--mep-neg)',
  };
  const semSoft = {
    pos: 'var(--mep-pos-soft)', warn: 'var(--mep-warn-soft)', neg: 'var(--mep-neg-soft)',
  };

  return (
    <main style={{ flex: 1, overflow: 'hidden', display: 'flex', flexDirection: 'column' }}>
      <div style={{ padding: '20px 24px 0', display: 'flex', flexDirection: 'column', gap: 14, flex: 1, minHeight: 0 }}>

        {/* Top — overall progress */}
        <div className="card" style={{ padding: '18px 20px',
          display: 'grid', gridTemplateColumns: '1.4fr 1fr 1fr 1fr', gap: 24, alignItems: 'center' }}>
          <div>
            <div className="label" style={{ marginBottom: 6 }}>Mayo 2026 · al día 19</div>
            <div style={{ display: 'flex', alignItems: 'baseline', gap: 10, marginBottom: 10 }}>
              <div className="num" style={{ fontSize: 32, fontWeight: 600, color: 'var(--mep-fg)', letterSpacing: -0.7, lineHeight: 1 }}>
                {BD.eurc(totalSpent)}
              </div>
              <div style={{ fontSize: 13, color: 'var(--mep-fg-3)' }}>
                de <span className="num" style={{ color: 'var(--mep-fg-2)', fontWeight: 500 }}>{BD.eurc(totalLimit)}</span>
              </div>
            </div>
            {/* Full-width segmented bar */}
            <div style={{ height: 8, borderRadius: 4, background: 'var(--mep-surface-2)', overflow: 'hidden',
              display: 'flex', position: 'relative' }}>
              {budgets.map((b, i) => {
                const w = (b.spent / totalLimit) * 100;
                return <span key={i} style={{
                  width: `${w}%`, height: '100%', background: b.color,
                  borderRight: i < budgets.length - 1 ? '1px solid var(--mep-bg)' : 'none',
                }} />;
              })}
              <div style={{ position: 'absolute', left: `${(totalSpent / totalLimit) * 100}%`,
                top: -3, bottom: -3, width: 1.5, background: 'var(--mep-fg)' }} />
            </div>
            <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: 11.5, color: 'var(--mep-fg-3)', marginTop: 8 }}>
              <span><span className="num" style={{ color: semColor[status(totalPct)], fontWeight: 600 }}>
                {totalPct.toFixed(1).replace('.', ',')}%
              </span> usado · proyección {(totalPct * 31 / 19).toFixed(0)}% al cierre</span>
              <span className="num">{BD.eurc(totalLimit - totalSpent)} restante</span>
            </div>
          </div>

          <BudgetTopStat label="Categorías" value={budgets.length}
            sub={`${budgets.filter(b => (b.spent / b.limit) * 100 > 100).length} sobrepasan presupuesto`}
            tone="warn" />
          <BudgetTopStat label="Mejor categoría" value="Vinos"
            sub="77% usado · 4 días extra de margen"
            tone="pos" />
          <BudgetTopStat label="Alerta global" value="80%"
            sub="Avisarme cuando una categoría llegue a este %"
            editable />
        </div>

        {/* Budget table */}
        <div className="card" style={{ padding: 0, overflow: 'hidden', flex: 1, display: 'flex', flexDirection: 'column' }}>
          <div style={{ padding: '12px 16px', display: 'flex', alignItems: 'center', justifyContent: 'space-between',
            borderBottom: '1px solid var(--mep-divider)' }}>
            <div>
              <div className="subtitle">Presupuesto por categoría</div>
              <div style={{ fontSize: 12, color: 'var(--mep-fg-3)', marginTop: 2 }}>
                Haz clic en una celda para editar
              </div>
            </div>
            <div style={{ display: 'flex', gap: 6, alignItems: 'center' }}>
              <button className="btn btn-ghost" style={{ height: 30, fontSize: 12.5 }}>
                <BI.RefreshCw size={12} /> Copiar de abril
              </button>
              <button className="btn btn-secondary"><BI.Download size={13} /> Exportar</button>
            </div>
          </div>

          <div style={{ overflow: 'auto', flex: 1 }}>
            <table className="tbl" style={{ tableLayout: 'fixed' }}>
              <thead>
                <tr>
                  <th style={{ width: '22%' }}>Categoría</th>
                  <th className="num" style={{ width: 130 }}>Presupuesto</th>
                  <th className="num" style={{ width: 130 }}>Gastado</th>
                  <th className="num" style={{ width: 130 }}>Restante</th>
                  <th style={{ width: '100%' }}>Progreso</th>
                  <th className="num" style={{ width: 80 }}>%</th>
                  <th style={{ width: 90 }}>Proyección</th>
                  <th style={{ width: 36 }}></th>
                </tr>
              </thead>
              <tbody>
                {budgets.map(b => {
                  const pct = (b.spent / b.limit) * 100;
                  const st = status(pct);
                  const projected = pct * 31 / 19;
                  const projOver = projected > 100;
                  return (
                    <tr key={b.cat} className="row">
                      <td>
                        <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                          <span style={{ width: 14, height: 14, borderRadius: 3, background: b.color, flexShrink: 0 }} />
                          <span style={{ fontSize: 13, fontWeight: 500, color: 'var(--mep-fg)' }}>{b.cat}</span>
                        </div>
                      </td>
                      <td className="num">
                        <EditableCell value={BD.eurc(b.limit)} />
                      </td>
                      <td className="num" style={{ color: 'var(--mep-fg-2)' }}>{BD.eur(b.spent)}</td>
                      <td className="num" style={{ color: st === 'neg' ? 'var(--mep-neg)' : 'var(--mep-fg-2)', fontWeight: st === 'neg' ? 500 : 400 }}>
                        {(b.limit - b.spent).toFixed(2).replace('.', ',')} €
                      </td>
                      <td>
                        <div style={{ position: 'relative', height: 8, borderRadius: 4,
                          background: 'var(--mep-surface-2)', overflow: 'visible' }}>
                          <div style={{
                            width: `${Math.min(pct, 100)}%`, height: '100%', borderRadius: 4,
                            background: semColor[st],
                          }} />
                          {/* over-budget tail */}
                          {pct > 100 && (
                            <div style={{
                              position: 'absolute', left: '100%', top: 0, bottom: 0,
                              width: `${Math.min(pct - 100, 40)}%`,
                              background: 'repeating-linear-gradient(45deg, var(--mep-neg), var(--mep-neg) 4px, var(--mep-neg-soft) 4px, var(--mep-neg-soft) 8px)',
                              borderRadius: '0 4px 4px 0',
                            }} />
                          )}
                          {/* target marker */}
                          <div style={{ position: 'absolute', left: '80%', top: -3, bottom: -3, width: 1.5,
                            background: 'var(--mep-fg-3)', opacity: 0.4 }} />
                        </div>
                      </td>
                      <td className="num" style={{ color: semColor[st], fontWeight: 600 }}>
                        {pct.toFixed(0)}%
                      </td>
                      <td>
                        <span style={{
                          fontSize: 11, fontWeight: 500, padding: '2px 6px', borderRadius: 4,
                          background: projOver ? 'var(--mep-neg-soft)' : 'var(--mep-pos-soft)',
                          color: projOver ? 'var(--mep-neg)' : 'var(--mep-pos)',
                          display: 'inline-flex', alignItems: 'center', gap: 3,
                        }} className="num">
                          {projOver ? '↑' : '✓'} {projected.toFixed(0)}%
                        </span>
                      </td>
                      <td>
                        <button className="btn btn-ghost" style={{ width: 22, height: 22, padding: 0, justifyContent: 'center' }}>
                          <BI.DotsH size={13} />
                        </button>
                      </td>
                    </tr>
                  );
                })}
                {/* Add row */}
                <tr>
                  <td colSpan={8} style={{ padding: '10px 12px',
                    background: 'var(--mep-surface-2)', cursor: 'pointer',
                    color: 'var(--mep-fg-3)', fontSize: 12.5, fontWeight: 500 }}>
                    <span style={{ display: 'inline-flex', alignItems: 'center', gap: 6 }}>
                      <BI.Plus size={12} /> Añadir categoría…
                    </span>
                  </td>
                </tr>
              </tbody>
              <tfoot>
                <tr>
                  <td colSpan={1} style={{ fontWeight: 600, color: 'var(--mep-fg)', fontSize: 13, padding: '12px' }}>Total</td>
                  <td className="num" style={{ fontWeight: 600, fontSize: 13 }}>{BD.eurc(totalLimit)}</td>
                  <td className="num" style={{ fontWeight: 600, fontSize: 13 }}>{BD.eurc(totalSpent)}</td>
                  <td className="num" style={{ fontWeight: 600, fontSize: 13, color: 'var(--mep-fg-2)' }}>{BD.eurc(totalLimit - totalSpent)}</td>
                  <td colSpan={2} className="num" style={{ fontWeight: 600, fontSize: 13, color: semColor[status(totalPct)] }}>
                    {totalPct.toFixed(1).replace('.', ',')}%
                  </td>
                  <td colSpan={2}></td>
                </tr>
              </tfoot>
            </table>
          </div>
        </div>

        {/* History toggle */}
        <div style={{ display: 'flex', alignItems: 'center', gap: 12, padding: '0 4px 16px' }}>
          <span style={{ fontSize: 12, color: 'var(--mep-fg-3)' }}>Ver mes anterior:</span>
          {['Feb', 'Mar', 'Abr'].map(m => (
            <button key={m} className="btn btn-ghost" style={{ height: 28, fontSize: 12, padding: '0 10px' }}>
              {m} 2026
            </button>
          ))}
        </div>
      </div>
    </main>
  );
}

function BudgetTopStat({ label, value, sub, tone, editable }) {
  return (
    <div style={{ borderLeft: '1px solid var(--mep-divider)', paddingLeft: 18 }}>
      <div className="label" style={{ marginBottom: 6 }}>{label}</div>
      <div className="num" style={{ fontSize: 22, fontWeight: 600,
        color: tone === 'warn' ? 'var(--mep-warn)' : tone === 'pos' ? 'var(--mep-pos)' : 'var(--mep-fg)',
        letterSpacing: -0.4, lineHeight: 1.1,
        display: 'inline-flex', alignItems: 'center', gap: 4,
      }}>
        {value}
        {editable && <BI.Edit size={13} style={{ color: 'var(--mep-fg-3)' }} />}
      </div>
      <div style={{ fontSize: 11.5, color: 'var(--mep-fg-3)', marginTop: 6 }}>{sub}</div>
    </div>
  );
}

function EditableCell({ value }) {
  return (
    <span style={{
      fontSize: 13, color: 'var(--mep-fg)', fontWeight: 500,
      padding: '3px 7px', borderRadius: 4, cursor: 'text',
      border: '1px dashed transparent',
      display: 'inline-block',
    }}>{value}</span>
  );
}

Object.assign(window, { MEPBudgets });

// src/routes/(app)/budgets/+page.svelte
<script lang="ts">
  import type { PageData } from './$types';
  import { enhance } from '$app/forms';
  import { locale, t } from '$lib/i18n';
  import { fmtEur, semColor } from '$lib/formatters';

  let { data }: { data: PageData } = $props();

  const today = new Date().getDate();

  let customCategories = $state<string[]>([]);
  let newCatName = $state('');
  let showAddForm = $state(false);

  const allCategories = $derived([...data.categories, ...customCategories]);

  function addCategory() {
    const name = newCatName.trim();
    if (!name || allCategories.includes(name)) return;
    customCategories.push(name);
    newCatName = '';
    showAddForm = false;
  }

  const rows = $derived(allCategories.map(cat => {
    const limit = data.budgets[cat] ?? 0;
    const spent = data.category_spend[cat] ?? 0;
    const pct   = limit > 0 ? (spent / limit) * 100 : 0;
    const remaining  = limit - spent;
    const projected  = today > 0 ? pct * 31 / today : 0;
    const color = data.colors[cat] ?? '#888';
    return { cat, limit, spent, pct, remaining, projected, color };
  }));

  const totalLimit = $derived(rows.reduce((s, r) => s + r.limit, 0));
  const totalSpent = $derived(rows.reduce((s, r) => s + r.spent, 0));
  const totalPct   = $derived(totalLimit > 0 ? (totalSpent / totalLimit) * 100 : 0);

  const monthLabel = $derived(new Date().toLocaleString($locale, { month: 'long', year: 'numeric' }));
</script>

<!-- ── Desktop layout ──────────────────────────────────────────────────── -->
<div class="hidden md:flex" style="height:100%;flex-direction:column;overflow:hidden;">
  <div style="padding:20px 24px 0;display:flex;flex-direction:column;gap:14px;flex:1;min-height:0;">

    <!-- Overall progress card -->
    <div class="card" style="padding:18px 20px;flex-shrink:0;">
      <div class="label" style="margin-bottom:6px;text-transform:capitalize;">{monthLabel} · al día {today}</div>
      <div style="display:flex;align-items:baseline;gap:10px;margin-bottom:10px;">
        <div class="num" style="font-size:32px;font-weight:600;color:var(--mep-fg);letter-spacing:-0.7px;line-height:1;">
          {fmtEur(totalSpent)}
        </div>
        <div style="font-size:13px;color:var(--mep-fg-3);">
          de <span class="num" style="color:var(--mep-fg-2);font-weight:500;">{fmtEur(totalLimit)}</span>
        </div>
      </div>
      {#if totalLimit > 0}
        <div style="height:8px;border-radius:4px;background:var(--mep-surface-2);overflow:hidden;display:flex;">
          {#each rows as r}
            {#if r.limit > 0}
              <span style="width:{(r.spent / totalLimit) * 100}%;height:100%;background:{r.color};border-right:1px solid var(--mep-bg);flex-shrink:0;"></span>
            {/if}
          {/each}
        </div>
        <div style="display:flex;justify-content:space-between;font-size:11.5px;color:var(--mep-fg-3);margin-top:8px;">
          <span>
            <span class="num" style="color:{semColor(totalPct)};font-weight:600;">{totalPct.toFixed(1).replace('.',',')}%</span>
            usado · proyección {(totalPct * 31 / today).toFixed(0)}% al cierre
          </span>
          <span class="num">{fmtEur(totalLimit - totalSpent)} restante</span>
        </div>
      {:else}
        <div style="font-size:13px;color:var(--mep-fg-3);">Define presupuestos mensuales por categoría para controlar tu gasto. Edita los campos en la tabla y guarda.</div>
      {/if}
    </div>

    <!-- Budget table -->
    <div class="card" style="padding:0;overflow:hidden;flex:1;display:flex;flex-direction:column;">
      <div style="padding:12px 16px;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid var(--mep-divider);flex-shrink:0;">
        <div>
          <div class="subtitle">Presupuesto por categoría</div>
          <div style="font-size:12px;color:var(--mep-fg-3);margin-top:2px;">Edita el campo de presupuesto y guarda</div>
        </div>
      </div>

      <div style="overflow:auto;flex:1;">
        <form method="post" action="?/save" use:enhance>
          <input type="hidden" name="_categories" value={JSON.stringify(allCategories)} />
          <table class="tbl" style="table-layout:fixed;">
            <thead>
              <tr>
                <th style="width:22%;">Categoría</th>
                <th class="num" style="width:160px;">Presupuesto</th>
                <th class="num" style="width:130px;">Gastado</th>
                <th class="num" style="width:130px;">Restante</th>
                <th style="min-width:120px;">Progreso</th>
                <th class="num" style="width:70px;">%</th>
                <th style="width:100px;">Proyección</th>
              </tr>
            </thead>
            <tbody>
              {#each rows as r}
                {@const projOver = r.limit > 0 && r.projected > 100}
                <tr class="row">
                  <td>
                    <div style="display:flex;align-items:center;gap:8px;">
                      <span style="width:14px;height:14px;border-radius:3px;background:{r.color};flex-shrink:0;"></span>
                      <span style="font-size:13px;font-weight:500;color:var(--mep-fg);">{r.cat}</span>
                    </div>
                  </td>
                  <td class="num">
                    <input type="number" step="0.01" min="0"
                      name={r.cat}
                      value={r.limit > 0 ? r.limit : ''}
                      placeholder={$t('bud.noLimit')}
                      class="input"
                      style="height:30px;font-size:12.5px;width:130px;text-align:right;" />
                  </td>
                  <td class="num" style="color:var(--mep-fg-2);">{fmtEur(r.spent)}</td>
                  <td class="num" style="color:{r.limit > 0 && r.remaining < 0 ? 'var(--mep-neg)' : 'var(--mep-fg-2)'};font-weight:{r.limit > 0 && r.remaining < 0 ? 500 : 400};">
                    {r.limit > 0 ? fmtEur(r.remaining) : '—'}
                  </td>
                  <td>
                    {#if r.limit > 0}
                      <div style="position:relative;height:8px;border-radius:4px;background:var(--mep-surface-2);overflow:visible;">
                        <div style="width:{Math.min(r.pct, 100)}%;height:100%;border-radius:4px;background:{semColor(r.pct)};"></div>
                        {#if r.pct > 100}
                          <div style="position:absolute;left:100%;top:0;bottom:0;width:{Math.min(r.pct - 100, 40)}%;
                            background:repeating-linear-gradient(45deg,var(--mep-neg),var(--mep-neg) 4px,var(--mep-neg-soft) 4px,var(--mep-neg-soft) 8px);
                            border-radius:0 4px 4px 0;"></div>
                        {/if}
                        <div style="position:absolute;left:80%;top:-3px;bottom:-3px;width:1.5px;background:var(--mep-fg-3);opacity:0.4;"></div>
                      </div>
                    {:else}
                      <span style="font-size:11.5px;color:var(--mep-fg-4);">Sin presupuesto</span>
                    {/if}
                  </td>
                  <td class="num" style="color:{r.limit > 0 ? semColor(r.pct) : 'var(--mep-fg-3)'};font-weight:600;">
                    {r.limit > 0 ? Math.round(r.pct) + '%' : '—'}
                  </td>
                  <td>
                    {#if r.limit > 0}
                      <span class="num" style="
                        font-size:11px;font-weight:500;padding:2px 6px;border-radius:4px;
                        background:{projOver ? 'var(--mep-neg-soft)' : 'var(--mep-pos-soft)'};
                        color:{projOver ? 'var(--mep-neg)' : 'var(--mep-pos)'};
                        display:inline-flex;align-items:center;gap:3px;
                      ">{projOver ? '↑' : '✓'} {Math.round(r.projected)}%</span>
                    {:else}
                      <span style="color:var(--mep-fg-4);font-size:11.5px;">—</span>
                    {/if}
                  </td>
                </tr>
              {/each}
              <!-- Add category row -->
              {#if showAddForm}
                <tr>
                  <td colspan={7} style="padding:8px 12px;background:var(--mep-surface-2);">
                    <div style="display:flex;align-items:center;gap:8px;">
                      <input
                        type="text" maxlength="80"
                        bind:value={newCatName}
                        placeholder="Nombre de categoría…"
                        class="input"
                        style="height:30px;font-size:12.5px;width:220px;"
                        onkeydown={(e) => { if (e.key === 'Enter') { e.preventDefault(); addCategory(); } }}
                      />
                      <button type="button" class="btn btn-primary" style="height:30px;font-size:12.5px;"
                        onclick={addCategory}>Añadir</button>
                      <button type="button" class="btn btn-ghost" style="height:30px;font-size:12.5px;"
                        onclick={() => { showAddForm = false; newCatName = ''; }}>Cancelar</button>
                    </div>
                  </td>
                </tr>
              {:else}
                <tr>
                  <td colspan={7} style="padding:0;background:var(--mep-surface-2);">
                    <button type="button"
                      style="width:100%;text-align:left;padding:10px 12px;cursor:pointer;color:var(--mep-fg-3);font-size:12.5px;font-weight:500;background:transparent;border:none;font:inherit;display:flex;align-items:center;gap:6px;"
                      onclick={() => showAddForm = true}>
                      <svg width="12" height="12" viewBox="0 0 12 12" fill="none" stroke="currentColor" stroke-width="1.8">
                        <line x1="6" y1="1" x2="6" y2="11"/><line x1="1" y1="6" x2="11" y2="6"/>
                      </svg>
                      {$t('bud.addCategory')}
                    </button>
                  </td>
                </tr>
              {/if}
            </tbody>
            {#if totalLimit > 0}
              <tfoot>
                <tr>
                  <td style="font-weight:600;color:var(--mep-fg);font-size:13px;padding:12px;">Total</td>
                  <td class="num" style="font-weight:600;font-size:13px;">{fmtEur(totalLimit)}</td>
                  <td class="num" style="font-weight:600;font-size:13px;">{fmtEur(totalSpent)}</td>
                  <td class="num" style="font-weight:600;font-size:13px;color:var(--mep-fg-2);">{fmtEur(totalLimit - totalSpent)}</td>
                  <td colspan={2} class="num" style="font-weight:600;font-size:13px;color:{semColor(totalPct)};">
                    {totalPct.toFixed(1).replace('.',',')}%
                  </td>
                  <td></td>
                </tr>
              </tfoot>
            {/if}
          </table>
          <div style="padding:14px 16px;border-top:1px solid var(--mep-divider);">
            <button type="submit" class="btn btn-primary" style="height:36px;">{$t('bud.save')}</button>
          </div>
        </form>
      </div>
    </div>

  </div>
</div>

<!-- ── Mobile layout ───────────────────────────────────────────────────── -->
<div class="flex md:hidden" style="height:100%;flex-direction:column;overflow:hidden;">
  <form method="post" action="?/save" use:enhance style="display:contents;">
    <input type="hidden" name="_categories" value={JSON.stringify(allCategories)} />

    <!-- Scrollable content -->
    <div style="flex:1;overflow-y:auto;padding:14px 16px 100px;display:flex;flex-direction:column;gap:12px;">

      <!-- Hero summary card -->
      <div class="card" style="padding:16px;">
        <div class="label" style="margin-bottom:6px;text-transform:capitalize;">{monthLabel} · al día {today}</div>
        <div style="display:flex;align-items:baseline;gap:8px;margin-bottom:10px;">
          <div class="num" style="font-size:30px;font-weight:600;color:var(--mep-fg);letter-spacing:-0.6px;line-height:1;">
            {fmtEur(totalSpent)}
          </div>
          <div style="font-size:12.5px;color:var(--mep-fg-3);">
            de <span class="num" style="color:var(--mep-fg-2);font-weight:500;">{fmtEur(totalLimit)}</span>
          </div>
        </div>
        {#if totalLimit > 0}
          <!-- Segmented bar -->
          <div style="height:8px;border-radius:4px;background:var(--mep-surface-2);overflow:hidden;display:flex;margin-bottom:10px;">
            {#each rows as r}
              {#if r.limit > 0}
                <span style="width:{(r.spent / totalLimit) * 100}%;height:100%;background:{r.color};border-right:1px solid var(--mep-bg);flex-shrink:0;"></span>
              {/if}
            {/each}
          </div>
          <div style="display:flex;justify-content:space-between;font-size:11.5px;color:var(--mep-fg-3);">
            <span>
              <span class="num" style="color:{semColor(totalPct)};font-weight:600;">{totalPct.toFixed(1).replace('.',',')}%</span>
              · proyección {(totalPct * 31 / today).toFixed(0)}% al cierre
            </span>
            <span class="num">{fmtEur(totalLimit - totalSpent)} restante</span>
          </div>
        {:else}
          <div style="font-size:13px;color:var(--mep-fg-3);">
            Define presupuestos por categoría para controlar tu gasto.
          </div>
        {/if}
      </div>

      <!-- Section header -->
      <div style="padding:4px 2px 0;">
        <div class="subtitle" style="font-size:14px;">Presupuesto por categoría</div>
      </div>

      <!-- Category cards -->
      {#each rows as r}
        {@const projOver = r.limit > 0 && r.projected > 100}
        <div class="card" style="padding:14px;">

          <!-- Top row: swatch + name + projection badge -->
          <div style="display:flex;align-items:center;gap:10px;margin-bottom:10px;">
            <span style="width:8px;height:28px;border-radius:2px;background:{r.color};flex-shrink:0;"></span>
            <span style="flex:1;font-size:14px;font-weight:500;color:var(--mep-fg);
              overflow:hidden;text-overflow:ellipsis;white-space:nowrap;">{r.cat}</span>
            {#if r.limit > 0}
              <span class="num" style="
                font-size:11px;font-weight:500;padding:2px 7px;border-radius:4px;flex-shrink:0;
                background:{projOver ? 'var(--mep-neg-soft)' : 'var(--mep-pos-soft)'};
                color:{projOver ? 'var(--mep-neg)' : 'var(--mep-pos)'};
              ">{projOver ? '↑' : '✓'} {Math.round(r.projected)}% cierre</span>
            {/if}
          </div>

          <!-- Progress bar -->
          {#if r.limit > 0}
            <div style="position:relative;height:7px;border-radius:4px;background:var(--mep-surface-2);overflow:visible;margin-bottom:10px;">
              <div style="width:{Math.min(r.pct, 100)}%;height:100%;border-radius:4px;background:{semColor(r.pct)};"></div>
              {#if r.pct > 100}
                <div style="position:absolute;left:100%;top:0;bottom:0;width:{Math.min(r.pct - 100, 40)}%;
                  background:repeating-linear-gradient(45deg,var(--mep-neg),var(--mep-neg) 4px,var(--mep-neg-soft) 4px,var(--mep-neg-soft) 8px);
                  border-radius:0 4px 4px 0;"></div>
              {/if}
              <!-- 80% target marker -->
              <div style="position:absolute;left:80%;top:-3px;bottom:-3px;width:1.5px;background:var(--mep-fg-3);opacity:0.4;"></div>
            </div>
          {/if}

          <!-- Amounts row: spent · % · remaining -->
          <div style="display:flex;align-items:center;justify-content:space-between;margin-bottom:10px;">
            <div>
              <span class="num" style="font-size:13.5px;font-weight:600;color:var(--mep-fg);">{fmtEur(r.spent)}</span>
              {#if r.limit > 0}
                <span style="font-size:11.5px;color:var(--mep-fg-3);"> · {fmtEur(r.limit)}</span>
              {/if}
            </div>
            <span class="num" style="font-size:13.5px;font-weight:600;color:{r.limit > 0 ? semColor(r.pct) : 'var(--mep-fg-3)'};">
              {r.limit > 0 ? Math.round(r.pct) + '%' : '—'}
            </span>
          </div>

          <!-- Budget input -->
          <div style="display:flex;align-items:center;gap:8px;">
            <label style="font-size:11px;color:var(--mep-fg-3);font-weight:500;white-space:nowrap;">Presupuesto</label>
            <input type="number" step="0.01" min="0"
              name={r.cat}
              value={r.limit > 0 ? r.limit : ''}
              placeholder={$t('bud.noLimit')}
              class="input"
              style="flex:1;height:34px;font-size:13px;text-align:right;" />
          </div>
        </div>
      {/each}

      <!-- Add category card (mobile) -->
      {#if showAddForm}
        <div class="card" style="padding:14px;display:flex;flex-direction:column;gap:10px;">
          <div style="font-size:13px;font-weight:500;color:var(--mep-fg);">Nueva categoría</div>
          <input
            type="text" maxlength="80"
            bind:value={newCatName}
            placeholder="Nombre de categoría…"
            class="input"
            style="height:40px;font-size:14px;"
            onkeydown={(e) => { if (e.key === 'Enter') { e.preventDefault(); addCategory(); } }}
          />
          <div style="display:flex;gap:8px;">
            <button type="button" class="btn btn-primary"
              style="flex:2;height:40px;justify-content:center;font-size:14px;"
              onclick={addCategory}>Añadir</button>
            <button type="button" class="btn btn-ghost"
              style="flex:1;height:40px;justify-content:center;font-size:14px;"
              onclick={() => { showAddForm = false; newCatName = ''; }}>Cancelar</button>
          </div>
        </div>
      {:else}
        <button type="button" class="card"
          style="padding:14px;display:flex;align-items:center;gap:10px;
            border:1.5px dashed var(--mep-divider);background:transparent;
            color:var(--mep-fg-3);font-size:13.5px;font-weight:500;
            width:100%;cursor:pointer;font-family:inherit;"
          onclick={() => showAddForm = true}>
          <svg width="16" height="16" viewBox="0 0 16 16" fill="none" stroke="currentColor" stroke-width="1.8">
            <line x1="8" y1="2" x2="8" y2="14"/><line x1="2" y1="8" x2="14" y2="8"/>
          </svg>
          Añadir categoría
        </button>
      {/if}

    </div>

    <!-- Sticky save button -->
    <div style="
      position:sticky;bottom:0;left:0;right:0;
      padding:12px 16px;
      background:var(--mep-bg);
      border-top:1px solid var(--mep-divider);
    ">
      <button type="submit" class="btn btn-primary"
        style="width:100%;height:44px;justify-content:center;font-size:15px;font-weight:600;">
        {$t('bud.save')}
      </button>
    </div>

  </form>
</div>
